use std::{env, fs::File, io::Write, path::PathBuf};

fn main() {
    // Configure defmt sink buffer size
    println!("cargo:rerun-if-env-changed=DEFMT_SINK_BUFFER_SIZE");

    let size = env::var("DEFMT_SINK_BUFFER_SIZE")
        .map(|s| {
            s.parse()
                .expect("could not parse DEFMT_SINK_BUFFER_SIZE as usize")
        })
        .unwrap_or(256_usize);

    let out_dir_path = PathBuf::from(env::var_os("OUT_DIR").unwrap());
    let out_file_path = out_dir_path.join("defmt_sink_consts.rs");
    let mut out_file = File::create(&out_file_path).unwrap();

    out_file
        .write_all(
            format!(
                "// Generated by build.rs\npub const DEFMT_SINK_BUF_SIZE: usize = {};\n",
                size
            )
            .as_bytes(),
        )
        .unwrap();

    out_file.flush().unwrap();
}
